# Generated by Django 3.2.12 on 2023-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikecount',
            field=models.IntegerField(blank=True, default=0, verbose_name='dislike_count'),
        ),
    ]
